---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# RXDMoD - R API for XDMoD Data Analytics Framework
Version: 1.0.0

As part of the XDMoD Data Analytics Framework, this R package
provides API access to the data warehouse of an instance of
XDMoD.
    

<!-- badges: start -->
<!-- badges: end -->

The goal of rxdmod is to ...

## Installation

You can install the development version of rxdmod from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ubccr/rxdmod")
```

## Example

```{r example,results='hide',message=FALSE,warning=FALSE}
library(tidyverse)
library(plotly)

# replace xdmod-notebooks with conda enviroment for python to use
library(reticulate)
use_condaenv("xdmod-notebooks")

library(rxdmod)
```

```{r}
# Get XDMoD connection
dw <- xdmod_get_datawarehouse('https://xdmod.access-ci.org')

# Get Data of Interest
df <- xdmod_get_data(dw,
        duration=c('2023-01-01', '2023-03-31'),
        realm='Jobs',
        metric='Number of Users: Active'
    )
```

Plot the data

```{r}
ggplot(df, aes(x=Time,y=`Number of Users: Active`)) +
        geom_line()
```
